#!/bin/bash

echo "=== Скрипт развертывания на VPS ==="
echo ""
echo "1. Создайте архив проекта:"
echo "   tar -czf medical-center.tar.gz --exclude=node_modules --exclude=.git --exclude=.next ."
echo ""
echo "2. Скопируйте архив на сервер:"
echo "   scp medical-center.tar.gz root@89.111.170.219:/var/www/medical-center/"
echo ""
echo "3. Подключитесь к серверу:"
echo "   ssh root@89.111.170.219"
echo ""
echo "4. Выполните команды на сервере:"
echo "   cd /var/www/medical-center"
echo "   tar -xzf medical-center.tar.gz"
echo "   rm medical-center.tar.gz"
echo "   npm install"
echo "   npm run build"
echo "   mkdir -p logs"
echo "   pm2 stop medical-center-app 2>/dev/null || true"
echo "   pm2 delete medical-center-app 2>/dev/null || true"
echo "   pm2 start ecosystem.config.js --env production"
echo "   pm2 save"
echo "   pm2 startup"
echo ""
echo "5. Настройте Nginx (если нужно):"
echo "   cp nginx.conf /etc/nginx/sites-available/medical-center"
echo "   ln -s /etc/nginx/sites-available/medical-center /etc/nginx/sites-enabled/"
echo "   systemctl restart nginx"
echo ""
echo "6. Откройте файрвол:"
echo "   ufw allow 3000"
echo "   ufw allow 80"
echo "   ufw allow 443"
echo ""
echo "Приложение будет доступно по адресу: http://89.111.170.219:3000"
